<?php
/**
 * Copyright 2015 Adobe
 * All Rights Reserved.
 */
declare(strict_types=1);

namespace Magento\CatalogUrlRewrite\Test\Unit\Model\Category;

use Magento\Catalog\Model\Category;
use Magento\CatalogUrlRewrite\Model\Category\CanonicalUrlRewriteGenerator;
use Magento\CatalogUrlRewrite\Model\CategoryUrlPathGenerator;
use Magento\CatalogUrlRewrite\Model\CategoryUrlRewriteGenerator;
use Magento\Framework\TestFramework\Unit\Helper\ObjectManager;
use Magento\UrlRewrite\Model\UrlFinderInterface;
use Magento\UrlRewrite\Service\V1\Data\UrlRewrite;
use Magento\UrlRewrite\Service\V1\Data\UrlRewriteFactory;
use PHPUnit\Framework\MockObject\MockObject;
use PHPUnit\Framework\TestCase;

class CanonicalUrlRewriteGeneratorTest extends TestCase
{
    /** @var CanonicalUrlRewriteGenerator */
    protected $canonicalUrlRewriteGenerator;

    /** @var CategoryUrlPathGenerator|MockObject */
    protected $categoryUrlPathGenerator;

    /** @var Category|MockObject */
    protected $category;

    /** @var UrlRewriteFactory|MockObject */
    protected $urlRewriteFactory;

    /** @var UrlRewrite|MockObject */
    protected $urlRewrite;

    /** @var UrlFinderInterface|MockObject */
    private $urlFinder;

    protected function setUp(): void
    {
        $this->urlRewriteFactory = $this->getMockBuilder(UrlRewriteFactory::class)
            ->onlyMethods(['create'])
            ->disableOriginalConstructor()
            ->getMock();
        $this->urlRewrite = $this->getMockBuilder(UrlRewrite::class)
            ->disableOriginalConstructor()
            ->getMock();
        $this->category = $this->getMockBuilder(Category::class)
            ->disableOriginalConstructor()
            ->getMock();
        $this->categoryUrlPathGenerator = $this->getMockBuilder(
            CategoryUrlPathGenerator::class
        )->disableOriginalConstructor()
            ->getMock();
        $this->urlFinder = $this->getMockBuilder(UrlFinderInterface::class)
            ->disableOriginalConstructor()
            ->getMockForAbstractClass();
        $this->canonicalUrlRewriteGenerator = (new ObjectManager($this))->getObject(
            CanonicalUrlRewriteGenerator::class,
            [
                'categoryUrlPathGenerator' => $this->categoryUrlPathGenerator,
                'urlRewriteFactory' => $this->urlRewriteFactory,
                'urlFinder' => $this->urlFinder
            ]
        );
    }

    public function testGenerate()
    {
        $requestPath = 'category.html';
        $targetPath = 'target-path';
        $storeId = 'store_id';
        $categoryId = 'category_id';

        $this->category->method('getId')->willReturn($categoryId);
        $this->categoryUrlPathGenerator->method('getUrlPathWithSuffix')->willReturn($requestPath);
        $this->categoryUrlPathGenerator->method('getUrlPath')->willReturn('category');
        $this->categoryUrlPathGenerator->method('getCanonicalUrlPath')->willReturn($targetPath);
        $this->urlFinder->method('findOneByData')->willReturn(null);
        $this->urlRewrite->expects($this->any())->method('setStoreId')->with($storeId)->willReturnSelf();
        $this->urlRewrite->expects($this->any())->method('setEntityId')->with($categoryId)->willReturnSelf();
        $this->urlRewrite->expects($this->any())->method('setEntityType')
            ->with(CategoryUrlRewriteGenerator::ENTITY_TYPE)->willReturnSelf();
        $this->urlRewrite->expects($this->any())->method('setRequestPath')->with($requestPath)->willReturnSelf();
        $this->urlRewrite->expects($this->any())->method('setTargetPath')->with($targetPath)->willReturnSelf();
        $this->urlRewriteFactory->method('create')->willReturn($this->urlRewrite);
        $this->assertEquals(
            ['category.html_store_id' => $this->urlRewrite],
            $this->canonicalUrlRewriteGenerator->generate($storeId, $this->category)
        );
    }

    public function testSkipGenerationForCustomRewriteOnUnchangedCategoryPath()
    {
        $requestPath = 'category.html';
        $storeId = 1;
        $customRewrite = $this->getMockBuilder(UrlRewrite::class)
            ->disableOriginalConstructor()
            ->getMock();

        $this->category->method('getUrlPath')->willReturn('category');
        $this->categoryUrlPathGenerator->method('getUrlPathWithSuffix')->willReturn($requestPath);
        $this->categoryUrlPathGenerator->method('getUrlPath')->willReturn('category');
        $this->urlFinder->expects($this->once())
            ->method('findOneByData')
            ->with(
                [
                    UrlRewrite::REQUEST_PATH => $requestPath,
                    UrlRewrite::STORE_ID => $storeId,
                ]
            )
            ->willReturn($customRewrite);
        $customRewrite->method('getEntityType')->willReturn('custom');
        $customRewrite->method('getIsAutogenerated')->willReturn(0);
        $this->urlRewriteFactory->expects($this->never())->method('create');

        $this->assertEquals([], $this->canonicalUrlRewriteGenerator->generate($storeId, $this->category));
    }
}
